### ISSUE TITLE
Errors when launching this version of PR2

### ISSUE THREAD

**Issue by ghost** [pr2tools/pr2tools.github.io#1]
When i launched the index.html in Pale Moon browser (one of unique/few browsers that still run Flash files) and the SWF file showed errors like 'Error #2032', 'SuperLoader::load - A SecurityError has occurred.' when it booted up.

The actual game version is v165 which is, i believe, VERY different version that one inclided in your packet.

I wish the best for you on fixing this.

**Comment by pr2tools** [comment]
Hi, is there a particular reason why you need to use the client? As far as I know the original PR2 servers are still up and maintained.

**Comment by ghost** [comment]
> Hi, is there a particular reason why you need to use the client? As far as I know the original PR2 servers are still up and maintained.

Yep, as for 2 reasons:

1] I wanna play PR2 fully offline;

2] I really dislike the way they are dealing with this game;

I wish the best for you on helping me with this. =]

**Comment by pr2tools** [comment]
Ok, I updated pr2tools.github.io page with steps how you can run PR2 fully offline. The only thing is you need to archive the pr2 level txt you want to play. There is also a [large archive](https://mega.nz/folder/VNRgUKRK#X8yxcHdrewIyCsw1MiqeiQ) with all 6 million levels from 2016. If you unpack it it will be 80GB, not sure if you want that.

Tell me if the offline server works for you. I'm also curious what exactly makes you dislike the way they are dealing with the game.
